baseURL: "https://juliuschanjq.github" 
title: Julius Chan
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 1
        - name: Projects
          url: projects/
          weight: 2
        - name: Report
          url: report/
          weight: 3
        - name: Resume
          url: CV/
          weight: 4

params:
    description: "I am a Professor of Subject at the University of Place. My research covers various topics.
consequat."
    author: Julius Chan
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Julius Chan
          subtitle: "Hey There!👋 I'm Julius, a tech enthusiast with a diverse portfolio of professional, personal, and academic projects. With professional experience in various tech domains and a Graduate in Computer Science, Applied Artificial Intelligence and Business Intelligence, I bring a wealth of expertise to the table, including strong product/project management and tech support skills. Whether it's discussing potential collaborations, sharing insights, or simply exchanging ideas, I'm always open to connecting with like-minded individuals."
          imageUrl: "photo_6168235905584839753_y.jpg"
          imageHeight: 240
          imageTitle: 
          buttons:
            - name: Papers
              url: papers/
            - name: Reports
              url: reports/
            - name: Projects
              url: projects/
            - name: Resume
              url: cv.pdf

    socialIcons:
        - name: LinkedIn
          url: https://www.linkedin.com/in/julius-chan/
        - name: Email
          url: mailto:juliuschanjq@gmail.com
        - name: GitHub
          url: https://github.com/juliuschanjq

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Julius"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
